# permissions for end users to view dynamicclusterroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kuberbac
    app.kubernetes.io/managed-by: kustomize
  name: dynamicclusterrole-viewer-role
rules:
- apiGroups:
  - kuberbac.prosimcorp.com
  resources:
  - dynamicclusterroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberbac.prosimcorp.com
  resources:
  - dynamicclusterroles/status
  verbs:
  - get
