# permissions for end users to edit dynamicrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kuberbac
    app.kubernetes.io/managed-by: kustomize
  name: dynamicrolebinding-editor-role
rules:
- apiGroups:
  - kuberbac.prosimcorp.com
  resources:
  - dynamicrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberbac.prosimcorp.com
  resources:
  - dynamicrolebindings/status
  verbs:
  - get
