# permissions for end users to edit dynamicclusterroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kuberbac
    app.kubernetes.io/managed-by: kustomize
  name: dynamicclusterrole-editor-role
rules:
- apiGroups:
  - kuberbac.prosimcorp.com
  resources:
  - dynamicclusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberbac.prosimcorp.com
  resources:
  - dynamicclusterroles/status
  verbs:
  - get
